#include "widget/batchautogeneratedialog.h"

#include <QBoxLayout>
#include <QFileDialog>
#include <QDateTime>
#include <QDir>

BatchAutoGenerateDialog::BatchAutoGenerateDialog(QWidget *parent)
    : QDialog(parent)
{
    setWindowTitle(tr("批量自动编写 T 语言模型"));
    setWindowModality(Qt::NonModal);
    resize(720, 520);

    auto *mainLayout = new QVBoxLayout(this);

    // Log file chooser
    auto *logLayout = new QHBoxLayout();
    auto *logLabel = new QLabel(tr("日志文件:"));
    m_logPathEdit = new QLineEdit();
    m_logPathEdit->setReadOnly(true);
    m_btnBrowse = new QPushButton(tr("选择日志..."));
    m_btnNewLog = new QPushButton(tr("新建日志"));
    logLayout->addWidget(logLabel);
    logLayout->addWidget(m_logPathEdit);
    logLayout->addWidget(m_btnBrowse);
    logLayout->addWidget(m_btnNewLog);
    mainLayout->addLayout(logLayout);

    // Status info
    m_statusLabel = new QLabel(tr("状态: 等待开始"));
    m_currentLabel = new QLabel(tr("当前器件: -"));
    m_progressBar = new QProgressBar();
    m_progressBar->setRange(0, 100);
    m_progressBar->setValue(0);
    m_progressBar->setTextVisible(true);
    m_progressBar->setFormat(tr("0 / 0 (0%)"));

    mainLayout->addWidget(m_statusLabel);
    mainLayout->addWidget(m_currentLabel);
    mainLayout->addWidget(m_progressBar);

    // Log viewer
    m_logViewer = new QPlainTextEdit();
    m_logViewer->setReadOnly(true);
    m_logViewer->setMinimumHeight(260);
    mainLayout->addWidget(m_logViewer);

    // Buttons
    auto *btnLayout = new QHBoxLayout();
    btnLayout->addStretch();
    m_btnStart = new QPushButton(tr("开始"));
    m_btnStop = new QPushButton(tr("停止"));
    m_btnClose = new QPushButton(tr("关闭"));
    m_btnStop->setEnabled(false);
    btnLayout->addWidget(m_btnStart);
    btnLayout->addWidget(m_btnStop);
    btnLayout->addWidget(m_btnClose);
    mainLayout->addLayout(btnLayout);

    connect(m_btnBrowse, &QPushButton::clicked, this, &BatchAutoGenerateDialog::onBrowseLog);
    connect(m_btnNewLog, &QPushButton::clicked, this, &BatchAutoGenerateDialog::onNewLog);
    connect(m_btnStart, &QPushButton::clicked, this, &BatchAutoGenerateDialog::onStart);
    connect(m_btnStop, &QPushButton::clicked, this, &BatchAutoGenerateDialog::onStop);
    connect(m_btnClose, &QPushButton::clicked, this, &QDialog::accept);

    // Default log path
    setLogPath(makeDefaultLogPath(), false);
}

QString BatchAutoGenerateDialog::logPath() const
{
    return m_logPathEdit->text().trimmed();
}

bool BatchAutoGenerateDialog::resumeMode() const
{
    return m_resumeMode;
}

void BatchAutoGenerateDialog::setLogPath(const QString &path, bool resume)
{
    m_logPathEdit->setText(path);
    m_resumeMode = resume;
    QString modeText = resume ? tr(" (追加)") : tr(" (新建)");
    appendLog(tr("日志文件: %1%2").arg(path, modeText));
}

void BatchAutoGenerateDialog::appendLog(const QString &text)
{
    m_logViewer->appendPlainText(text);
    m_logViewer->ensureCursorVisible();
}

void BatchAutoGenerateDialog::updateProgress(int current, int total)
{
    if (total <= 0) {
        m_progressBar->setRange(0, 100);
        m_progressBar->setValue(0);
        m_progressBar->setFormat(tr("0 / 0 (0%)"));
        return;
    }

    if (m_progressBar->maximum() != total)
        m_progressBar->setRange(0, total);

    m_progressBar->setValue(current);
    double percent = static_cast<double>(current) * 100.0 / static_cast<double>(total);
    m_progressBar->setFormat(tr("%1 / %2 (%3%)")
                                 .arg(current)
                                 .arg(total)
                                 .arg(QString::number(percent, 'f', 1)));
}

void BatchAutoGenerateDialog::setStatus(const QString &status)
{
    m_statusLabel->setText(tr("状态: %1").arg(status));
}

void BatchAutoGenerateDialog::setCurrentEquipment(const QString &info)
{
    m_currentLabel->setText(tr("当前器件: %1").arg(info));
}

void BatchAutoGenerateDialog::setRunning(bool running)
{
    m_btnStart->setEnabled(!running);
    m_btnBrowse->setEnabled(!running);
    m_btnNewLog->setEnabled(!running);
    m_btnStop->setEnabled(running);
    m_btnClose->setEnabled(!running);
    if (!running) {
        setStatus(tr("已停止"));
        m_currentLabel->setText(tr("当前器件: -"));
    }
}

void BatchAutoGenerateDialog::onBrowseLog()
{
    QString path = QFileDialog::getOpenFileName(this, tr("选择日志文件"), QDir::currentPath(), tr("日志文件 (*.log *.txt);;所有文件 (*.*)"));
    if (path.isEmpty())
        return;
    setLogPath(path, true);
}

void BatchAutoGenerateDialog::onNewLog()
{
    setLogPath(makeDefaultLogPath(), false);
}

void BatchAutoGenerateDialog::onStart()
{
    QString path = logPath();
    if (path.isEmpty()) {
        path = makeDefaultLogPath();
        setLogPath(path, false);
    }
    appendLog(tr("开始执行，日志文件：%1").arg(path));
    setRunning(true);
    emit startRequested(path, m_resumeMode);
}

void BatchAutoGenerateDialog::onStop()
{
    emit stopRequested();
}

QString BatchAutoGenerateDialog::makeDefaultLogPath() const
{
    QDir dir(QDir::currentPath());
    QString fileName = QString("batch_autogen_%1.log").arg(QDateTime::currentDateTime().toString("yyyyMMdd_hhmmss"));
    return dir.filePath(fileName);
}
