#ifndef BATCHAUTOGENERATEDIALOG_H
#define BATCHAUTOGENERATEDIALOG_H

#include <QDialog>
#include <QPlainTextEdit>
#include <QProgressBar>
#include <QPushButton>
#include <QLineEdit>
#include <QCheckBox>
#include <QLabel>
#include <QTabWidget>
#include <QSplitter>
#include <QMap>
#include <QSpinBox>
#include <QScrollBar>

// Worker Tab 页的内容
struct WorkerTabContent {
    QWidget *tabWidget;          // Tab 页容器
    QPlainTextEdit *logViewer;   // 工作日志（包含输入输出）
    QPlainTextEdit *streamViewer; // AI 流式输出
};

class BatchAutoGenerateDialog : public QDialog
{
    Q_OBJECT
public:
    explicit BatchAutoGenerateDialog(QWidget *parent = nullptr);

    QString logPath() const;
    bool resumeMode() const;
    bool enableWorkerLog() const;     // 是否启用 Worker 详细日志
    int threadCount() const;          // 获取线程数配置

    void setLogPath(const QString &path, bool resume);
    void appendLog(const QString &text);  // 追加到 Manager 主日志
    void updateProgress(int current, int total);
    void setStatus(const QString &status);
    void setCurrentEquipment(const QString &info);
    void setRunning(bool running);
    
    // Worker Tab 管理
    void createWorkerTab(int workerId, const QString &code, const QString &name);
    void appendWorkerLog(int workerId, const QString &text);
    void appendWorkerStream(int workerId, const QString &text);
    void closeWorkerTab(int workerId);
    void closeAllWorkerTabs();  // 关闭所有 Worker Tab

signals:
    void startRequested(const QString &logPath, bool resumeExisting);
    void stopRequested();

private slots:
    void onBrowseLog();
    void onNewLog();
    void onStart();
    void onStop();

private:
    QLineEdit *m_logPathEdit;
    QPushButton *m_btnBrowse;
    QPushButton *m_btnNewLog;
    QPushButton *m_btnStart;
    QPushButton *m_btnStop;
    QPushButton *m_btnClose;
    QLabel *m_statusLabel;
    QLabel *m_currentLabel;
    QProgressBar *m_progressBar;
    
    QTabWidget *m_tabWidget;           // Tab 容器
    QPlainTextEdit *m_managerLogViewer; // Manager 主日志（在第一个 Tab）
    QMap<int, WorkerTabContent> m_workerTabs; // workerId -> Tab 内容
    
    // 新增配置项
    QCheckBox *m_chkEnableWorkerLog;   // 是否启用 Worker 详细日志文件
    QSpinBox *m_spinThreadCount;       // 线程数配置
    
    bool m_resumeMode = false;
    int m_lastActiveTabIndex = -1;     // 记录用户最后选择的 Tab 索引，-1 表示跟随更新

    QString makeDefaultLogPath() const;
    void ensureButtons();
    QWidget* createWorkerTabWidget(QPlainTextEdit **logViewer, QPlainTextEdit **streamViewer);
};

#endif // BATCHAUTOGENERATEDIALOG_H
