#ifndef BATCHAUTOGENERATEDIALOG_H
#define BATCHAUTOGENERATEDIALOG_H

#include <QDialog>
#include <QPlainTextEdit>
#include <QProgressBar>
#include <QPushButton>
#include <QLineEdit>
#include <QCheckBox>
#include <QLabel>

class BatchAutoGenerateDialog : public QDialog
{
    Q_OBJECT
public:
    explicit BatchAutoGenerateDialog(QWidget *parent = nullptr);

    QString logPath() const;
    bool resumeMode() const;

    void setLogPath(const QString &path, bool resume);
    void appendLog(const QString &text);
    void updateProgress(int current, int total);
    void setStatus(const QString &status);
    void setCurrentEquipment(const QString &info);
    void setRunning(bool running);

signals:
    void startRequested(const QString &logPath, bool resumeExisting);
    void stopRequested();

private slots:
    void onBrowseLog();
    void onNewLog();
    void onStart();
    void onStop();

private:
    QLineEdit *m_logPathEdit;
    QPushButton *m_btnBrowse;
    QPushButton *m_btnNewLog;
    QPushButton *m_btnStart;
    QPushButton *m_btnStop;
    QPushButton *m_btnClose;
    QLabel *m_statusLabel;
    QLabel *m_currentLabel;
    QProgressBar *m_progressBar;
    QPlainTextEdit *m_logViewer;
    bool m_resumeMode = false;

    QString makeDefaultLogPath() const;
    void ensureButtons();
};

#endif // BATCHAUTOGENERATEDIALOG_H
