#include "diagnosistree.h"

DiagnosisTree::DiagnosisTree()
    : m_treeId(0)
    , m_containerId(0)
    , m_functionId(0)
    , m_rootNodeId(0)
    , m_autoGenerated(true)
    , m_rootNode(nullptr)
    , m_fullTreeLoaded(false)
{
}

DiagnosisTree::~DiagnosisTree()
{
    clearTree();
}

bool DiagnosisTree::loadFromDatabase(QSqlDatabase &db, int treeId)
{
    QSqlQuery query(db);
    query.prepare("SELECT * FROM diagnosis_tree WHERE tree_id = ?");
    query.addBindValue(treeId);

    if (!query.exec()) {
        qDebug() << "Failed to load diagnosis tree:" << query.lastError().text();
        return false;
    }

    if (!query.next()) {
        qDebug() << "Diagnosis tree not found:" << treeId;
        return false;
    }

    m_treeId = query.value("tree_id").toInt();
    m_containerId = query.value("container_id").toInt();
    m_functionId = query.value("function_id").toInt();
    m_name = query.value("name").toString();
    m_description = query.value("description").toString();
    m_rootNodeId = query.value("root_node_id").toInt();
    m_createdTime = QDateTime::fromString(query.value("created_time").toString(), Qt::ISODate);
    m_autoGenerated = query.value("auto_generated").toBool();

    return true;
}

bool DiagnosisTree::loadByFunctionId(QSqlDatabase &db, int functionId)
{
    QSqlQuery query(db);
    query.prepare("SELECT * FROM diagnosis_tree WHERE function_id = ? LIMIT 1");
    query.addBindValue(functionId);

    if (!query.exec()) {
        qDebug() << "Failed to load diagnosis tree by function_id:" << query.lastError().text();
        return false;
    }

    if (!query.next()) {
        qDebug() << "Diagnosis tree not found for function_id:" << functionId;
        return false;
    }

    m_treeId = query.value("tree_id").toInt();
    m_containerId = query.value("container_id").toInt();
    m_functionId = query.value("function_id").toInt();
    m_name = query.value("name").toString();
    m_description = query.value("description").toString();
    m_rootNodeId = query.value("root_node_id").toInt();
    m_createdTime = QDateTime::fromString(query.value("created_time").toString(), Qt::ISODate);
    m_autoGenerated = query.value("auto_generated").toBool();

    return true;
}

bool DiagnosisTree::saveToDatabase(QSqlDatabase &db)
{
    QSqlQuery query(db);
    query.prepare(
        "INSERT INTO diagnosis_tree "
        "(container_id, function_id, name, description, root_node_id, created_time, auto_generated) "
        "VALUES (?, ?, ?, ?, ?, ?, ?)"
    );

    query.addBindValue(m_containerId);
    query.addBindValue(m_functionId > 0 ? m_functionId : QVariant());
    query.addBindValue(m_name);
    query.addBindValue(m_description);
    query.addBindValue(m_rootNodeId > 0 ? m_rootNodeId : QVariant());
    query.addBindValue(m_createdTime.toString(Qt::ISODate));
    query.addBindValue(m_autoGenerated ? 1 : 0);

    if (!query.exec()) {
        qDebug() << "Failed to save diagnosis tree:" << query.lastError().text();
        return false;
    }

    m_treeId = query.lastInsertId().toInt();
    return true;
}

bool DiagnosisTree::updateToDatabase(QSqlDatabase &db)
{
    if (m_treeId == 0) {
        qDebug() << "Cannot update tree without valid ID";
        return false;
    }

    QSqlQuery query(db);
    query.prepare(
        "UPDATE diagnosis_tree SET "
        "container_id = ?, function_id = ?, name = ?, description = ?, "
        "root_node_id = ?, created_time = ?, auto_generated = ? "
        "WHERE tree_id = ?"
    );

    query.addBindValue(m_containerId);
    query.addBindValue(m_functionId > 0 ? m_functionId : QVariant());
    query.addBindValue(m_name);
    query.addBindValue(m_description);
    query.addBindValue(m_rootNodeId > 0 ? m_rootNodeId : QVariant());
    query.addBindValue(m_createdTime.toString(Qt::ISODate));
    query.addBindValue(m_autoGenerated ? 1 : 0);
    query.addBindValue(m_treeId);

    if (!query.exec()) {
        qDebug() << "Failed to update diagnosis tree:" << query.lastError().text();
        return false;
    }

    return true;
}

bool DiagnosisTree::deleteFromDatabase(QSqlDatabase &db)
{
    if (m_treeId == 0) {
        qDebug() << "Cannot delete tree without valid ID";
        return false;
    }

    // 级联删除由外键约束自动处理
    QSqlQuery query(db);
    query.prepare("DELETE FROM diagnosis_tree WHERE tree_id = ?");
    query.addBindValue(m_treeId);

    if (!query.exec()) {
        qDebug() << "Failed to delete diagnosis tree:" << query.lastError().text();
        return false;
    }

    clearTree();
    return true;
}

bool DiagnosisTree::loadFullTree(QSqlDatabase &db)
{
    // 首先加载根节点
    if (m_rootNodeId == 0) {
        qDebug() << "No root node ID specified";
        return false;
    }

    clearTree();
    m_rootNode = new DiagnosisTreeNode();
    if (!m_rootNode->loadFromDatabase(db, m_rootNodeId)) {
        delete m_rootNode;
        m_rootNode = nullptr;
        return false;
    }

    // 递归加载所有子节点
    loadChildNodes(db, m_rootNode);
    m_fullTreeLoaded = true;
    return true;
}

int DiagnosisTree::loadChildNodes(QSqlDatabase &db, DiagnosisTreeNode* node)
{
    if (!node) return 0;

    QSqlQuery query(db);
    query.prepare("SELECT node_id FROM diagnosis_tree_node WHERE parent_node_id = ?");
    query.addBindValue(node->nodeId());

    if (!query.exec()) {
        qDebug() << "Failed to load child nodes:" << query.lastError().text();
        return 0;
    }

    int count = 0;
    while (query.next()) {
        int childId = query.value("node_id").toInt();
        DiagnosisTreeNode* childNode = new DiagnosisTreeNode();
        
        if (childNode->loadFromDatabase(db, childId)) {
            node->addChild(childNode);
            count++;
            // 递归加载子节点的子节点
            count += loadChildNodes(db, childNode);
        } else {
            delete childNode;
        }
    }

    return count;
}

bool DiagnosisTree::saveFullTree(QSqlDatabase &db)
{
    if (!m_rootNode) {
        qDebug() << "No root node to save";
        return false;
    }

    // 首先保存树信息（如果是新树）
    if (m_treeId == 0) {
        if (!saveToDatabase(db)) {
            return false;
        }
    }

    // 递归保存所有节点
    if (!saveNodeRecursive(db, m_rootNode)) {
        return false;
    }

    // 更新root_node_id
    m_rootNodeId = m_rootNode->nodeId();
    if (!updateToDatabase(db)) {
        return false;
    }

    return true;
}

bool DiagnosisTree::saveNodeRecursive(QSqlDatabase &db, DiagnosisTreeNode* node)
{
    if (!node) return true;

    // 设置树ID
    node->setTreeId(m_treeId);

    // 保存当前节点
    if (node->nodeId() == 0) {
        if (!node->saveToDatabase(db)) {
            return false;
        }
    } else {
        if (!node->updateToDatabase(db)) {
            return false;
        }
    }

    // 递归保存子节点
    for (DiagnosisTreeNode* child : node->children()) {
        child->setParentNodeId(node->nodeId());
        if (!saveNodeRecursive(db, child)) {
            return false;
        }
    }

    return true;
}

void DiagnosisTree::clearTree()
{
    if (m_rootNode) {
        delete m_rootNode;
        m_rootNode = nullptr;
    }
    m_fullTreeLoaded = false;
}

DiagnosisTreeNode* DiagnosisTree::findNodeById(int nodeId) const
{
    if (!m_rootNode) return nullptr;
    return findNodeByIdRecursive(m_rootNode, nodeId);
}

DiagnosisTreeNode* DiagnosisTree::findNodeByIdRecursive(DiagnosisTreeNode* node, int nodeId) const
{
    if (!node) return nullptr;
    if (node->nodeId() == nodeId) return node;

    for (DiagnosisTreeNode* child : node->children()) {
        DiagnosisTreeNode* found = findNodeByIdRecursive(child, nodeId);
        if (found) return found;
    }

    return nullptr;
}

QList<DiagnosisTreeNode*> DiagnosisTree::getAllLeafNodes() const
{
    QList<DiagnosisTreeNode*> leaves;
    if (m_rootNode) {
        collectLeafNodesRecursive(m_rootNode, leaves);
    }
    return leaves;
}

void DiagnosisTree::collectLeafNodesRecursive(DiagnosisTreeNode* node, QList<DiagnosisTreeNode*> &leaves) const
{
    if (!node) return;

    if (node->isLeaf()) {
        leaves.append(node);
    } else {
        for (DiagnosisTreeNode* child : node->children()) {
            collectLeafNodesRecursive(child, leaves);
        }
    }
}

QList<DiagnosisTreeNode*> DiagnosisTree::getAllTestNodes() const
{
    QList<DiagnosisTreeNode*> tests;
    if (m_rootNode) {
        collectTestNodesRecursive(m_rootNode, tests);
    }
    return tests;
}

void DiagnosisTree::collectTestNodesRecursive(DiagnosisTreeNode* node, QList<DiagnosisTreeNode*> &tests) const
{
    if (!node) return;

    if (node->isTestNode()) {
        tests.append(node);
    }

    for (DiagnosisTreeNode* child : node->children()) {
        collectTestNodesRecursive(child, tests);
    }
}

int DiagnosisTree::countNodes() const
{
    return countNodesRecursive(m_rootNode);
}

int DiagnosisTree::countNodesRecursive(DiagnosisTreeNode* node) const
{
    if (!node) return 0;

    int count = 1; // 当前节点
    for (DiagnosisTreeNode* child : node->children()) {
        count += countNodesRecursive(child);
    }
    return count;
}

int DiagnosisTree::maxDepth() const
{
    return maxDepthRecursive(m_rootNode, 0);
}

int DiagnosisTree::maxDepthRecursive(DiagnosisTreeNode* node, int currentDepth) const
{
    if (!node) return currentDepth;

    int maxD = currentDepth;
    for (DiagnosisTreeNode* child : node->children()) {
        int d = maxDepthRecursive(child, currentDepth + 1);
        if (d > maxD) maxD = d;
    }
    return maxD;
}

bool DiagnosisTree::validateTree() const
{
    if (!m_rootNode) {
        qDebug() << "Tree validation failed: no root node";
        return false;
    }

    // 检查根节点ID是否匹配
    if (m_rootNodeId != 0 && m_rootNode->nodeId() != m_rootNodeId) {
        qDebug() << "Tree validation failed: root node ID mismatch";
        return false;
    }

    // 检查所有节点的tree_id是否一致
    // 这里可以添加更多验证逻辑

    return true;
}

void DiagnosisTree::debugPrintTree() const
{
    qDebug() << "=== Diagnosis Tree ===" << m_name;
    qDebug() << "Tree ID:" << m_treeId;
    qDebug() << "Function ID:" << m_functionId;
    qDebug() << "Total nodes:" << countNodes();
    qDebug() << "Max depth:" << maxDepth();
    qDebug() << "\nTree structure:";
    
    if (m_rootNode) {
        m_rootNode->debugPrint(0);
    } else {
        qDebug() << "  (no root node loaded)";
    }
}

QList<DiagnosisTreeNode*> DiagnosisTree::getAllNodes() const
{
    QList<DiagnosisTreeNode*> allNodes;
    if (m_rootNode) {
        collectAllNodesRecursive(m_rootNode, allNodes);
    }
    return allNodes;
}

void DiagnosisTree::collectAllNodesRecursive(DiagnosisTreeNode* node, QList<DiagnosisTreeNode*> &allNodes) const
{
    if (!node) return;

    allNodes.append(node);

    for (DiagnosisTreeNode* child : node->children()) {
        collectAllNodesRecursive(child, allNodes);
    }
}
