#ifndef DIAGNOSISTREE_H
#define DIAGNOSISTREE_H

#include <QString>
#include <QDateTime>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
#include <QDebug>
#include "diagnosistreenode.h"

/**
 * @brief 诊断树数据对象类
 * 
 * 对应数据库表 diagnosis_tree
 * 管理整个诊断决策树的结构和元数据
 */
class DiagnosisTree
{
public:
    DiagnosisTree();
    ~DiagnosisTree();

    // ===== 基本属性访问 =====
    int treeId() const { return m_treeId; }
    void setTreeId(int id) { m_treeId = id; }

    int containerId() const { return m_containerId; }
    void setContainerId(int id) { m_containerId = id; }

    int functionId() const { return m_functionId; }
    void setFunctionId(int id) { m_functionId = id; }

    QString name() const { return m_name; }
    void setName(const QString &name) { m_name = name; }

    QString description() const { return m_description; }
    void setDescription(const QString &desc) { m_description = desc; }

    int rootNodeId() const { return m_rootNodeId; }
    void setRootNodeId(int id) { m_rootNodeId = id; }

    QDateTime createdTime() const { return m_createdTime; }
    void setCreatedTime(const QDateTime &time) { m_createdTime = time; }

    bool isAutoGenerated() const { return m_autoGenerated; }
    void setAutoGenerated(bool autoGen) { m_autoGenerated = autoGen; }

    DiagnosisTreeNode* rootNode() const { return m_rootNode; }
    void setRootNode(DiagnosisTreeNode* root) { m_rootNode = root; }

    // ===== 数据库操作 =====
    /**
     * @brief 从数据库加载诊断树基本信息（不包括节点）
     * @param db 数据库连接
     * @param treeId 树ID
     * @return 成功返回true
     */
    bool loadFromDatabase(QSqlDatabase &db, int treeId);

    /**
     * @brief 根据功能ID从数据库加载诊断树
     * @param db 数据库连接
     * @param functionId 功能ID
     * @return 成功返回true
     */
    bool loadByFunctionId(QSqlDatabase &db, int functionId);

    /**
     * @brief 保存诊断树到数据库（不包括节点）
     * @param db 数据库连接
     * @return 成功返回true
     */
    bool saveToDatabase(QSqlDatabase &db);

    /**
     * @brief 更新诊断树到数据库
     * @param db 数据库连接
     * @return 成功返回true
     */
    bool updateToDatabase(QSqlDatabase &db);

    /**
     * @brief 从数据库删除诊断树及所有节点
     * @param db 数据库连接
     * @return 成功返回true
     */
    bool deleteFromDatabase(QSqlDatabase &db);

    // ===== 树结构操作 =====
    /**
     * @brief 加载完整的树结构（递归加载所有节点）
     * @param db 数据库连接
     * @return 成功返回true
     */
    bool loadFullTree(QSqlDatabase &db);

    /**
     * @brief 保存完整的树结构到数据库（递归保存所有节点）
     * @param db 数据库连接
     * @return 成功返回true
     */
    bool saveFullTree(QSqlDatabase &db);

    /**
     * @brief 从根节点递归加载子节点
     * @param db 数据库连接
     * @param node 父节点
     * @return 加载的子节点数量
     */
    int loadChildNodes(QSqlDatabase &db, DiagnosisTreeNode* node);

    /**
     * @brief 递归保存节点及其子节点
     * @param db 数据库连接
     * @param node 要保存的节点
     * @return 成功返回true
     */
    bool saveNodeRecursive(QSqlDatabase &db, DiagnosisTreeNode* node);

    /**
     * @brief 清空树结构（删除所有节点对象）
     */
    void clearTree();

    // ===== 查询操作 =====
    /**
     * @brief 根据节点ID查找节点
     * @param nodeId 节点ID
     * @return 找到返回节点指针，否则返回nullptr
     */
    DiagnosisTreeNode* findNodeById(int nodeId) const;

    /**
     * @brief 获取所有叶子节点（故障结论节点）
     * @return 叶子节点列表
     */
    QList<DiagnosisTreeNode*> getAllLeafNodes() const;

    /**
     * @brief 获取所有测试节点
     * @return 测试节点列表
     */
    QList<DiagnosisTreeNode*> getAllTestNodes() const;

    /**
     * @brief 获取所有节点（递归遍历）
     * @return 所有节点列表
     */
    QList<DiagnosisTreeNode*> getAllNodes() const;

    /**
     * @brief 统计树中的节点总数
     * @return 节点数量
     */
    int countNodes() const;

    /**
     * @brief 获取树的最大深度
     * @return 深度值
     */
    int maxDepth() const;

    /**
     * @brief 验证树结构的完整性
     * @return 如果树结构有效返回true
     */
    bool validateTree() const;

    // ===== 辅助方法 =====
    /**
     * @brief 打印整个树结构（用于调试）
     */
    void debugPrintTree() const;

    /**
     * @brief 检查是否已加载完整树结构
     */
    bool isFullTreeLoaded() const { return m_fullTreeLoaded; }

private:
    // 递归辅助方法
    DiagnosisTreeNode* findNodeByIdRecursive(DiagnosisTreeNode* node, int nodeId) const;
    void collectLeafNodesRecursive(DiagnosisTreeNode* node, QList<DiagnosisTreeNode*> &leaves) const;
    void collectTestNodesRecursive(DiagnosisTreeNode* node, QList<DiagnosisTreeNode*> &tests) const;
    void collectAllNodesRecursive(DiagnosisTreeNode* node, QList<DiagnosisTreeNode*> &allNodes) const;
    int countNodesRecursive(DiagnosisTreeNode* node) const;
    int maxDepthRecursive(DiagnosisTreeNode* node, int currentDepth) const;

    // 数据库字段
    int m_treeId;
    int m_containerId;
    int m_functionId;
    QString m_name;
    QString m_description;
    int m_rootNodeId;
    QDateTime m_createdTime;
    bool m_autoGenerated;

    // 树结构
    DiagnosisTreeNode* m_rootNode;
    bool m_fullTreeLoaded;
};

#endif // DIAGNOSISTREE_H
